Mitaka v3
Snergster/virl-salt pull request #91
Opened 2016-09-29 13:48 UTC by virlos

Ok, I can still see diffs that have just v3 switched for v2.0, but later on it's parametrized.

2016-09-29 21:06 UTC, Snergster requested changes
some vinstall improvements that ill still take if done in mitaka.vinstall.py ...but should be functionally complete (as in I've added or redone the functionality represented here

2016-09-29 21:06 UTC, Snergster commented on common/salt-minion/files/modules.keystone.py
> -    auth_url = get('auth_url', 'http://127.0.0.1:35357/v2.0/')
this entire file will not be used with mitaka...we are hopefully going to be able to use defaults for all states and modules unless they don't exist or we have custom changes needed like glance

2016-09-29 21:06 UTC, Snergster commented on _modules/virl_core.py
> -OS_AUTH_URL = 'http://localhost:5000/v2.0'
I'm now going to set OS_AUTH_URL so this backward incompatible change is not required

2016-09-29 21:06 UTC, Snergster commented on common/salt-minion/files/openstack.conf
> -keystone.auth_url: 'http://127.0.0.1:5000/v2.0/'
im not seeing this file get used anywhere...are you?

2016-09-29 21:06 UTC, Snergster commented on files/cinder.conf.jinja
> +auth_uri = http://{{ salt['pillar.get']('virl:hostname', salt['grains.get']('hostname', 'virl')) }}:5000/v3
this file is deprecated...i put changes in new mitaka version of cinder.conf under openstack/cinder/files

2016-09-29 21:06 UTC, Snergster commented on openstack/cinder/files/api-paste.ini
> +auth_uri = http://{{ salt['pillar.get']('virl:hostname', salt['grains.get']('hostname', 'virl')) }}:5000/v3
im not installing this file now...but I've created a mitaka specific file in case we start

2016-09-29 21:06 UTC, Snergster commented on openstack/cinder/files/cinder.conf
> +auth_uri = http://{{ salt['pillar.get']('virl:hostname', salt['grains.get']('hostname', 'virl')) }}:5000/v3
see above about this file being replaced

2016-09-29 21:06 UTC, Snergster commented on openstack/neutron/create-basic.sls
> +{% from "virl.jinja" import virl with context %}
ok this is all cooked in now

2016-09-29 21:06 UTC, Snergster commented on openstack/neutron/delete-basic.sls
> +{% set log_str = "--os-tenant-name admin --os-username admin --os-password %s --os-auth-url=http://%s%s/v3" % (ospassword, controllerip, ':5000') %}
baked this in as well...bit concerned that log_str is going to hold up though

2016-09-29 21:06 UTC, Snergster commented on openstack/neutron/files/kilo.neutron.conf
> +nova_admin_auth_url = http://{{ salt['pillar.get']('virl:internalnet_controller_ip', salt['grains.get']('internalnet_controller_ip', 'virl')) }}:35357/{{ virl.keystone_auth_version }}
there was already a sep mitaka.neutron.conf  so the needed changes were made there

2016-09-29 21:06 UTC, Snergster commented on openstack/neutron/files/mitaka.neutron.conf
> +#auth_uri = http://127.0.0.1:35357/v3/
needed changes were ONLY made in mitaka.nova.conf  just leaving kilo alone

2016-09-29 21:06 UTC, Snergster commented on openstack/neutron/files/mitaka/neutron+common+utils.py
> +    return '%s/v3/' % auth_uri
done

2016-09-29 21:06 UTC, Snergster commented on openstack/neutron/init.sls
> +    - value: 'http://{{ virl.controllerhostname }}:35357/v3'
put these in the proper way

2016-09-29 21:06 UTC, Snergster commented on openstack/nova/files/compute.nova.conf
> +neutron_admin_auth_url = http://{{ salt['pillar.get']('virl:internalnet_controller_ip', salt['grains.get']('internalnet_controller_ip', '172.16.10.250')) }}:35357/v3
baked in properly

2016-09-29 21:06 UTC, Snergster commented on openstack/nova/files/kilo.nova.conf
> +neutron_admin_auth_url = http://{{ salt['pillar.get']('virl:internalnet_controller_ip', salt['grains.get']('hostname', '172.16.10.250')) }}:35357/{{ virl.keystone_auth_version }}
not touching kilo

2016-09-29 21:06 UTC, Snergster commented on openstack/nova/files/mitaka.nova.conf
> +neutron_admin_auth_url = http://{{ salt['pillar.get']('virl:internalnet_controller_ip', salt['grains.get']('hostname', '172.16.10.250')) }}:35357/v3
added in properly

2016-09-29 21:06 UTC, Snergster commented on openstack/nova/files/nova.conf
> +neutron_admin_auth_url = http://{{ salt['pillar.get']('virl:hostname', salt['grains.get']('hostname', 'virl')) }}:35357/{{ virl.keystone_auth_version }}
this is a dead file pending sep

2016-09-29 21:06 UTC, Snergster commented on virl.jinja
> +    'keystone_auth_version' : salt['pillar.get']('virl:keystone_auth_version', salt['grains.get']('keystone_auth_version', 'v2.0' ))
inserted

2016-09-29 21:06 UTC, Snergster commented on virl/files/vextra.py
> +keystone.auth_url: 'http://127.0.0.1:5000/v3/'
leaving this alone for now...this will be overwritten...vextra is just the basest of bootstraps

2016-09-29 21:06 UTC, Snergster commented on virl/files/vinstall.py
> +    safeparser.read(safeparser_file)
nice catch..thx

2016-09-29 21:06 UTC, Snergster commented on virl/files/vinstall.py
> +keystone_auth_urlv2 = 'http://localhost:5000/v2.0'
i did these bits a different way and going to leave it unless you find bugs

2016-09-29 21:06 UTC, Snergster commented on virl/files/vinstall.py
> +qadmincall = ['/usr/bin/neutron', '--os-tenant-name', '{0}'.format(os_tenant_name), '--os-username', '{0}'.format(os_username), '--os-password',
there some good changes in here...but please merge to latest and then put in a new pr....

put it against mitaka.vinstall.py though

2016-09-29 21:06 UTC, Snergster commented on virl/files/virl-openrc.sh
> +export OS_AUTH_URL=http://controller:35357/v3
this should be fixed now...totally different way but fixed

2016-09-29 21:06 UTC, Snergster commented on virl/openvpn/lockdown.sls
> +{% from "virl.jinja" import virl with context %}
this file is done

2016-09-29 21:06 UTC, Snergster commented on virl/openvpn/packet.sls
> +    - name: neutron --os-tenant-name admin --os-username admin --os-password {{ virl.ospassword }} --os-auth-url=http://127.0.1.1:5000/{{ virl.keystone_auth_version }} subnet-update flat --gateway_ip
done

2016-09-29 21:06 UTC, Snergster commented on virl/std/install.sls
> +    - name: /usr/local/bin/virl_uwm_server init -A http://127.0.1.1:5000/{{ virl.keystone_auth_version }} -u uwmadmin -p {{ virl.uwmpassword }} -U uwmadmin -P {{ virl.uwmpassword }} -T uwmadmin
done

2016-09-29 21:06 UTC, Snergster commented on virl/std/config/virl_user_management.sls
> +      - crudini --set /etc/virl/virl.cfg env virl_openstack_auth_url http://localhost:5000/v3
done albeit different

2016-09-30 14:04 UTC, Snergster commented on openstack/keystone/install.sls
> +{% if virl.mitaka %}
this change is not needed...as dealing with the different rc was already done

2016-09-30 14:04 UTC, Snergster commented on openstack/keystone/files/admin-openrc.jinja
> +#export OS_PROJECT_DOMAIN_ID=default
done

2016-09-30 14:08 UTC, Snergster commented on virl/std/install.sls
> +      - crudini --set /etc/virl/virl.cfg env virl_openstack_auth_url http://localhost:5000/{{ virl.keystone_auth_version }}
done

2016-09-30 14:08 UTC, Snergster commented on virl/std/config/virl_user_management.sls
>        - crudini --set /etc/virl/virl.cfg env virl_uwm_url http://localhost:{{ uwmport }}
extracted out into if

2016-09-30 14:09 UTC, Snergster commented on virl/files/vinstall.py
> +# can be chosen by looking at kilo variable too
no i don't see a reason to have either of these in settings so not sure why they would be needed here

2016-09-30 14:13 UTC, closed without merging

2016-10-01 06:33 UTC, asloboda-cisco commented
Current virlos/mitaka-v3 bootstraps on trusty and xenial.  There is a caveat though.  In addition of requiring keystone_auth_version=v3 in virl.ini (should be only needed for xenial as v2.0 is default) it will fail to install images.  minion.d/openstack.conf has keystone auth url set to v3 and it breaks salt glance module.  I have not figured out why that happens, everything else seems to be passing without issues so far.  Reverting to v2.0 fixes image installation but we are set out to use v3 for all of mitaka.

2016-10-03 10:05 UTC, asloboda-cisco commented
We traced this to salt keystone module which has hardcoded import of v2_0 in /usr/lib/python2.7/dist-packages/salt/modules/keystone.py.  We can get through by patching it to import v3 instead and that works.  We also tried importing generic version and setting version to 3 but that does not seem to have service_catalog to retrieve endpoint and does not get through.

I'm not sure if patching salt keystone module is what we want and if it is we either need to patch or not patch based on the platform or need some way say which one to import.

2016-10-03 10:33 UTC, asloboda-cisco commented
And now nova.flavor_create is broken too, this time beyond easy repair it seems as there's a lot of black magic going on in novaclient authentication.  Works with 2.0 but with v3 tries to access /v3/v2.0/tokens, it doesn't know anything about v3 authentication.

2016-10-06 06:46 UTC, asloboda-cisco commented on common/salt-minion/files/openstack.conf
> -keystone.auth_url: 'http://127.0.0.1:5000/v2.0/'
can I delete it or do you have plans with it?

2016-10-06 06:52 UTC, asloboda-cisco commented on openstack/cinder/files/api-paste.ini
> +auth_uri = http://{{ salt['pillar.get']('virl:hostname', salt['grains.get']('hostname', 'virl')) }}:5000/v3
I don't like this policy of "do not fix unused files and let unsuspecting people be surprised later".  BTW it should have been parametrized with keystone_auth_version, all of this should have, this pull request was incomplete...

2016-10-06 06:54 UTC, asloboda-cisco commented on openstack/cinder/files/cinder.conf
> +auth_uri = http://{{ salt['pillar.get']('virl:hostname', salt['grains.get']('hostname', 'virl')) }}:5000/v3
I see this one being installed in install.sls

2016-10-06 06:57 UTC, asloboda-cisco commented on openstack/neutron/files/kilo.neutron.conf
> +nova_admin_auth_url = http://{{ salt['pillar.get']('virl:internalnet_controller_ip', salt['grains.get']('internalnet_controller_ip', 'virl')) }}:35357/{{ virl.keystone_auth_version }}
reverting back to hardcoded values

2016-10-06 07:03 UTC, asloboda-cisco commented on openstack/nova/files/nova.conf
> +neutron_admin_auth_url = http://{{ salt['pillar.get']('virl:hostname', salt['grains.get']('hostname', 'virl')) }}:35357/{{ virl.keystone_auth_version }}
reverting

2016-10-06 07:11 UTC, asloboda-cisco commented on virl/files/vinstall.py
> +keystone_auth_urlv2 = 'http://localhost:5000/v2.0'
We can't use v3 for mitaka minion.d/openstack.conf, mitaka vinstall is inserting v2.0.  Everything else though should be parametrized, whatever is in vinstall and mitaka.install now seems to be working.  On the other hand what you have seems to create a mix of both v2.0 and v3 which is still breaking stuff.

2016-10-06 07:15 UTC, asloboda-cisco commented on virl/files/virl-openrc.sh
> +export OS_AUTH_URL=http://controller:35357/v3
I don't see this file being used anywhere.  BTW you seem to be setting OS_SERVICE_ENDPOINT to v3 which breaks at least CLI keystone endpoint-list.

2016-10-06 07:26 UTC, asloboda-cisco commented on virl/std/config/virl_user_management.sls
>        - crudini --set /etc/virl/virl.cfg env virl_uwm_url http://localhost:{{ uwmport }}
Ok, next time we'll be tracking down all these hardcoded values again...

2016-10-06 07:40 UTC, asloboda-cisco commented on virl/files/vinstall.py
> +# can be chosen by looking at kilo variable too
I don't see a reason to maintain two copies of vinstall, but reverting to hardcoded url now.

2016-10-06 07:57 UTC, asloboda-cisco commented on _modules/virl_core.py
> -OS_AUTH_URL = 'http://localhost:5000/v2.0'
Counting on it then, removing altogether.

2016-10-06 08:00 UTC, asloboda-cisco commented on _modules/virl_core.py
> -OS_AUTH_URL = 'http://localhost:5000/v2.0'
Wait a second, I don't see you reading it from env in your tree.   Only reverting.